### ISSUE TITLE
ARM Boot parameter

### ISSUE THREAD

**Issue by worldwidemv** [wildtechgarden/www-wildtechgarden#34]
Hello,

thanks for your page: devel/arm-devel/arm-libvirt-kvm-virtualization/uefi-manual-arm-for-libvirt-kvm/

The Section "Enable VM (domain) Boot into Debian" helped a lot!

However, the command is not correct since it misses a `boot`.
So the working command is: `bcfg boot add 0 FS0:EFI\debian\grubarm.efi "Linux"`

Thanks, bye

**Comment by danielfdickinson** [comment]
Thank you for letting me know that I missed that in the write-up!

I'll fix that soon.

Regards,
Daniel

Daniel F. Dickinson<https://www.danielfdickinson.ca/> (he/him/they/them)
B. Computing
Wild Tech 'Garden'<https://www.wildtechgarden.ca/>

________________________________
From: worldwidemv ***@***.***>
Sent: November 24, 2023 11:44 AM
To: wildtechgarden/www-wildtechgarden ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [wildtechgarden/www-wildtechgarden] ARM Boot parameter (Issue #34)


Hello,

thanks for your page: devel/arm-devel/arm-libvirt-kvm-virtualization/uefi-manual-arm-for-libvirt-kvm/

The Section "Enable VM (domain) Boot into Debian" helped a lot!

However, the command is not correct since it misses a boot.
So the working command is: bcfg boot add 0 FS0:EFI\debian\grubarm.efi "Linux"

Thanks, bye

**Comment by danielfdickinson** [comment]
Fixed, and thank you again for letting me know.
